### ISSUE TITLE
ajouter generateur

### ISSUE THREAD

**Issue by mastilver** [AkibaTech/Analytics-Spammers#1]
Bonjour

Projet interessant.
Cependant vous devez tout faire a la main. (Il y a deja une difference entre le htaccess et le nginx)
Je souhaite donc ajouter un generateur utilisant handlebar (ou une autre technologie).
Du NodeJs vous derange t-il?

**Comment by MarceauKa** [comment]
Bonjour, merci de votre retour.
J'utilise un petit script pour mon htaccess. Pas pour NGINX.
Mais non, Node.js ne me dérange pas :)

**Comment by mastilver** [comment]
ok super ;)
j'ai profite de ma pause dej pour commencer, je vous envoie une PR ce soir

**Comment by MarceauKa** [comment]
Super ! Merci pour la contribution.
Concernant les extensions qui ont disparues, c'est normal. Il s'avère que les spammeurs ont souvent le même domaine mais avec des extensions différentes ".ml", ".ru", ".ga", ...
C'est pour cette raison que j'ai préféré faire un wildcard sur les extensions.

**Comment by mastilver** [comment]
serait-il possible de le publier sur npm? ;)

**Comment by MarceauKa** [comment]
Voilà qui est fait :)
https://www.npmjs.com/package/analytics-spammers

**Comment by mastilver** [comment]
cool!
